/**
 * ChatSessionManager — manages multiple parallel chat sessions.
 * Each session has its own queue, history, autopilot state, and waiting flag.
 */
import type { ChatSession, QueuedPrompt, ToolCallEntry } from "./webviewTypes";

export class ChatSessionManager {
	private sessions: Map<string, ChatSession> = new Map();
	private activeSessionId: string | null = null;
	private deletedSessionIds: Set<string> = new Set();

	private isAutoGeneratedTitle(title: string | undefined): boolean {
		if (!title) return true;
		const trimmed = title.trim();
		return (
			trimmed.length === 0 ||
			trimmed === "New Session" ||
			/^Conversation\s+\S+$/.test(trimmed)
		);
	}

	public getNextSessionId(): string {
		let maxSessionNumber = 0;
		for (const session of this.sessions.values()) {
			if (!/^\d+$/.test(session.id)) continue;
			const value = Number(session.id);
			if (Number.isFinite(value)) {
				maxSessionNumber = Math.max(maxSessionNumber, value);
			}
		}
		return String(maxSessionNumber + 1);
	}

	public getNextAgentTitle(): string {
		let maxAgentNumber = 0;
		for (const session of this.sessions.values()) {
			const match = /^Agent\s+(\d+)$/.exec(session.title.trim());
			if (!match) continue;
			const value = Number(match[1]);
			if (Number.isFinite(value)) {
				maxAgentNumber = Math.max(maxAgentNumber, value);
			}
		}
		return `Agent ${maxAgentNumber + 1}`;
	}

	private buildSession(
		id: string,
		title: string,
		overrides?: Partial<ChatSession>,
	): ChatSession {
		const baseSession: ChatSession = {
			id,
			title,
			status: "active",
			queue: [],
			queueEnabled: true,
			history: [],
			attachments: [],
			autopilotEnabled: false,
			waitingOnUser: false,
			createdAt: Date.now(),
			pendingToolCallId: null,
			sessionStartTime: null,
			sessionFrozenElapsed: null,
			sessionTerminated: false,
			sessionWarningShown: false,
			aiTurnActive: false,
			consecutiveAutoResponses: 0,
			autopilotIndex: 0,
		};

		return {
			...baseSession,
			...overrides,
			queue: overrides?.queue ? [...overrides.queue] : [...baseSession.queue],
			history: overrides?.history
				? [...overrides.history]
				: [...baseSession.history],
			attachments: overrides?.attachments
				? [...overrides.attachments]
				: [...baseSession.attachments],
		};
	}

	private hydrateSession(
		raw: Partial<ChatSession> & Pick<ChatSession, "id">,
	): ChatSession {
		const rawTitle = typeof raw.title === "string" ? raw.title : "";
		const title = this.isAutoGeneratedTitle(rawTitle)
			? this.getNextAgentTitle()
			: rawTitle;
		return this.buildSession(raw.id, title, {
			status: raw.status === "archived" ? "archived" : "active",
			queue: Array.isArray(raw.queue) ? raw.queue : [],
			queueEnabled: raw.queueEnabled !== false,
			history: Array.isArray(raw.history) ? raw.history : [],
			attachments: Array.isArray(raw.attachments) ? raw.attachments : [],
			autopilotEnabled: raw.autopilotEnabled === true,
			...(typeof raw.autopilotText === "string"
				? { autopilotText: raw.autopilotText }
				: {}),
			...(Array.isArray(raw.autopilotPrompts)
				? {
						autopilotPrompts: raw.autopilotPrompts.filter(
							(s: unknown) => typeof s === "string" && s.trim().length > 0,
						),
					}
				: {}),
			...(typeof raw.autoAppendEnabled === "boolean"
				? { autoAppendEnabled: raw.autoAppendEnabled }
				: {}),
			...(typeof raw.autoAppendText === "string"
				? { autoAppendText: raw.autoAppendText }
				: {}),
			waitingOnUser: raw.waitingOnUser === true,
			createdAt:
				typeof raw.createdAt === "number" && Number.isFinite(raw.createdAt)
					? raw.createdAt
					: Date.now(),
			pendingToolCallId:
				typeof raw.pendingToolCallId === "string"
					? raw.pendingToolCallId
					: null,
			sessionStartTime:
				typeof raw.sessionStartTime === "number" &&
				Number.isFinite(raw.sessionStartTime)
					? raw.sessionStartTime
					: null,
			sessionFrozenElapsed:
				typeof raw.sessionFrozenElapsed === "number" &&
				Number.isFinite(raw.sessionFrozenElapsed)
					? raw.sessionFrozenElapsed
					: null,
			sessionTerminated: raw.sessionTerminated === true,
			sessionWarningShown: raw.sessionWarningShown === true,
			aiTurnActive: raw.aiTurnActive === true,
			consecutiveAutoResponses:
				typeof raw.consecutiveAutoResponses === "number" &&
				Number.isFinite(raw.consecutiveAutoResponses)
					? Math.max(0, Math.floor(raw.consecutiveAutoResponses))
					: 0,
			autopilotIndex:
				typeof raw.autopilotIndex === "number" &&
				Number.isFinite(raw.autopilotIndex)
					? Math.max(0, Math.floor(raw.autopilotIndex))
					: 0,
		});
	}

	/**
	 * Create a new chat session and set it as the active session.
	 */
	public createSession(
		title: string = this.getNextAgentTitle(),
		id: string = this.getNextSessionId(),
		overrides?: Partial<ChatSession>,
		activate: boolean = true,
	): ChatSession {
		const session = this.buildSession(id, title, overrides);
		this.sessions.set(id, session);
		if (activate) {
			this.activeSessionId = id;
		}
		return session;
	}

	/**
	 * Get an existing session by ID or create one with that exact ID.
	 * If the ID was previously deleted, assigns a fresh ID instead of resurrecting the old one.
	 */
	public ensureSession(
		id: string,
		title: string = this.getNextAgentTitle(),
		overrides?: Partial<ChatSession>,
	): ChatSession {
		const existing = this.sessions.get(id);
		if (existing) {
			if (this.isAutoGeneratedTitle(existing.title)) {
				existing.title = this.isAutoGeneratedTitle(title)
					? this.getNextAgentTitle()
					: title;
			}
			return existing;
		}
		const resolvedTitle = this.isAutoGeneratedTitle(title)
			? this.getNextAgentTitle()
			: title;
		// Prevent resurrecting a deleted session — assign a fresh ID instead
		const resolvedId = this.deletedSessionIds.has(id)
			? this.getNextSessionId()
			: id;
		return this.createSession(resolvedTitle, resolvedId, overrides, false);
	}

	/**
	 * Get a session by ID.
	 */
	public getSession(id: string): ChatSession | undefined {
		return this.sessions.get(id);
	}

	/**
	 * Get the currently active (focused) session.
	 */
	public getActiveSession(): ChatSession | undefined {
		if (!this.activeSessionId) return undefined;
		return this.sessions.get(this.activeSessionId);
	}

	/**
	 * Get the active session ID.
	 */
	public getActiveSessionId(): string | null {
		return this.activeSessionId;
	}

	/**
	 * Set the active session by ID. Returns false if session not found, or true if null.
	 */
	public setActiveSession(id: string | null): boolean {
		if (id === null) {
			this.activeSessionId = null;
			return true;
		}
		if (!this.sessions.has(id)) return false;
		this.activeSessionId = id;
		return true;
	}

	/**
	 * Get all sessions as an array.
	 */
	public getAllSessions(): ChatSession[] {
		return Array.from(this.sessions.values());
	}

	/**
	 * Get only active (non-archived) sessions.
	 */
	public getActiveSessions(): ChatSession[] {
		return this.getAllSessions().filter((s) => s.status === "active");
	}

	/**
	 * Archive a session (mark as archived, keep data).
	 */
	public archiveSession(id: string): boolean {
		const session = this.sessions.get(id);
		if (!session) return false;
		session.status = "archived";
		// If the archived session was active, clear active
		if (this.activeSessionId === id) {
			// Find the next active session, or null
			const remaining = this.getActiveSessions();
			this.activeSessionId = remaining.length > 0 ? remaining[0].id : null;
		}
		return true;
	}

	/**
	 * Delete a session entirely.
	 */
	public deleteSession(id: string): boolean {
		const existed = this.sessions.delete(id);
		if (existed) {
			this.deletedSessionIds.add(id);
			if (this.activeSessionId === id) {
				const remaining = this.getActiveSessions();
				this.activeSessionId = remaining.length > 0 ? remaining[0].id : null;
			}
		}
		return existed;
	}

	public renameSession(id: string, title: string): boolean {
		const session = this.sessions.get(id);
		if (!session) return false;
		const trimmed = title.trim();
		if (trimmed.length === 0) return false;
		session.title = trimmed;
		return true;
	}

	/**
	 * Get the total number of sessions.
	 */
	public get size(): number {
		return this.sessions.size;
	}

	/**
	 * Get sessions that are waiting on user input (for pending inbox).
	 */
	public getWaitingSessions(): ChatSession[] {
		return this.getAllSessions().filter(
			(s) => s.status === "active" && s.waitingOnUser,
		);
	}

	/**
	 * Add a tool call entry to a specific session's history.
	 */
	public addHistoryEntry(sessionId: string, entry: ToolCallEntry): boolean {
		const session = this.sessions.get(sessionId);
		if (!session) return false;
		session.history.unshift(entry);
		return true;
	}

	/**
	 * Add a queued prompt to a specific session's queue.
	 */
	public addQueueItem(sessionId: string, item: QueuedPrompt): boolean {
		const session = this.sessions.get(sessionId);
		if (!session) return false;
		session.queue.push(item);
		return true;
	}

	/**
	 * Dequeue the first prompt from a session's queue.
	 */
	public dequeueItem(sessionId: string): QueuedPrompt | undefined {
		const session = this.sessions.get(sessionId);
		if (!session || session.queue.length === 0) return undefined;
		return session.queue.shift();
	}

	/**
	 * Serialize all sessions for persistence.
	 */
	public toJSON(): {
		sessions: ChatSession[];
		activeSessionId: string | null;
	} {
		return {
			sessions: this.getAllSessions(),
			activeSessionId: this.activeSessionId,
		};
	}

	/**
	 * Restore sessions from persisted data.
	 */
	public fromJSON(data: {
		sessions: ChatSession[];
		activeSessionId: string | null;
	}): void {
		// Preserve in-flight sessions (with pending tool calls) that were created
		// before disk load finished — avoids race where async loadSessionsFromDisk
		// wipes sessions created by concurrent ask_user tool calls.
		const inFlight = new Map<string, ChatSession>();
		for (const [id, session] of this.sessions) {
			if (session.pendingToolCallId) {
				inFlight.set(id, session);
			}
		}

		this.sessions.clear();
		for (const session of data.sessions) {
			if (!session?.id) continue;
			// Don't overwrite in-flight sessions with stale disk data
			if (inFlight.has(session.id)) continue;
			this.sessions.set(session.id, this.hydrateSession(session));
		}

		// Restore in-flight sessions
		for (const [id, session] of inFlight) {
			this.sessions.set(id, session);
		}

		this.activeSessionId = data.activeSessionId;
		// Validate active session still exists
		if (this.activeSessionId && !this.sessions.has(this.activeSessionId)) {
			const active = this.getActiveSessions();
			this.activeSessionId = active.length > 0 ? active[0].id : null;
		}
	}
}
